services:
  php-apache:
    build:
      context: ./docker/php
    container_name: symfony_web
    env_file:
      - ".env"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8080:80"
    volumes:
      - ./Symfony-spotify:/var/www/html
      - uploads-data:/var/www/html/public/uploads
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  # MariaDB
  database:
    image: mariadb:10.6
    container_name: symfony_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6

  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - "8085:8080"

  backup:
    image: mariadb:10.6 
    container_name: symfony_backup
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./docker/backup/backup.sh:/usr/local/bin/backup.sh
      - ./backup:/backup 
      - ./Symfony-spotify/public/uploads:/uploads:ro
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
    entrypoint: ["sh", "-c", "while true; do /usr/local/bin/backup.sh; echo 'Backup fait, dodo 1h...'; sleep 3600; done"]
    restart: unless-stopped

volumes:
  db-data:
  uploads-data:
